### REGISTER

POST http://localhost:4000/register
Content-Type: application/json

{
    "email" : "test1",  
    "password"  : "test1",
    "username"      : "test1",
    "firstName" :"test1",
    "lastName"  : "test1"
}


### LOGIN

POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "test1",
    "password" : "test1"
}